--insert into category values(1, 'Vegan')
--insert into category values(2, 'Vegetarian')
--insert into category values(3, 'Halal')
--insert into category values(4, 'Fruit')
--insert into category values(5, 'No-Gluten')
--insert into category values(6, 'General')
--id,category,current time,ingredient,instruction,name,serivings,category
--insert into recipex values(100, 'Fruit Salad', 4, 'Fruit Ingredient', 'Cut the fruits in cubes and serve', 4)
insert into recipex values(100, 'vegan',CURRENT_TIMESTAMP, 'Fruit Ingredient','Cut the fruits in cubes and serve','Fruit Salad', 4)
insert into recipex values(101, 'vegeterian',CURRENT_TIMESTAMP, 'Banana Bread Ingredient','make the dough and put in oven for 45 mins','Banana Bread', 10)
--insert into values(106, 'Banana Bread', 'src8.png', 'Banana Ingredient', 'Test 8', 4, 4)
--insert into recipex values(101, 'Stir Fry', 'src2.png', 'Vegan Ingredient', 'Test 2', 1)
--insert into recipex values(102, 'Lasagne', 'src3.png', 'Vegetarian Stock', 'Test 3', 2)
--insert into recipex values(103, 'Kebab', 'src1.png', 'Halal Ingredient', 'Test 1', 3)
--insert into recipex values(104, 'Ry Bread', 'src2.png', 'Gluten Free Bread', 'Test 2', 5)
--insert into recipex values(105, 'Beryani', 'src3.png', 'Apple n Onion', 'Test 3', 6)